travis:
  secure:
    BINSTAR_TOKEN: K4+wUWithJKC75DUnOOasgBovU8E25WsIaUOC3fhUt1A+XITqpLEMQyxWDR2VRC04UgLa8dANKG5FnI6sgcuKBtQoS/CY3ODHxlvZN6bagscptABz+/VThHY9p1Vr0LFBEu2vNZfcv5OQNTDLEWi5ogzQH5ZLrOCR8Nf5kAy4W5AUIGfZLpcbcs8WaDxGG/+Jg/B6dj9Pa6WGjwdqhiZqrSS7NUFtaH3vztkUiQOkLZAKmsSr3yokVn2UAVg/onFAZq9fdsfdIMJtLEb7NzQq117rLT0xL11oCy2JJnRDfmjeVymiMJcfd/TOPkn4cZb8McS33/Kn0HXIrJUF0TIcr1Hmi/81xI0sN0uz8RWHdH4bXW2jnAtfjs6MnstkkBdgL2PgrMOFfh6SN9mpmJwi5TAi7YBV27ZNdsHvuzbBaFh1okYJkX8PAPE5V9k+NF5kKJQDX+7PBc+sjfuRRKbuxCLNUjZNCDBhLW6ma29TsYKKojB+v8qrQmGICA//o1V7qch40C+aCdqkAtc3+gb7vopsnx7/QUC3DKcCY9edvEjcbLev2Yu5jjflng003dstqHk2e4XZKBO5fOtUIrl6j7mbZE+YApp1E/NYtl9rPcut09QAC2pEhFx5IUgfBUCl8ApmVGEgPNY6QoRPJjmaSKLpbBV4ULilnj/LPUllaY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
